package com.ajulay.endpoint;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:52.382+03:00
 * Generated source version: 3.2.7
 */
@WebServiceClient(name = "AssigneeSoapEndPointService",
        wsdlLocation = "http://localhost:8080/assignee?wsdl",
        targetNamespace = "http://endpoint.ajulay.com/")
public class AssigneeSoapEndPointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.ajulay.com/", "AssigneeSoapEndPointService");
    public final static QName AssigneeSoapEndPointPort = new QName("http://endpoint.ajulay.com/", "AssigneeSoapEndPointPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/assignee?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AssigneeSoapEndPointService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8080/assignee?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AssigneeSoapEndPointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AssigneeSoapEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AssigneeSoapEndPointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AssigneeSoapEndPointService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AssigneeSoapEndPointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AssigneeSoapEndPointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns AssigneeSoapEndPoint
     */
    @WebEndpoint(name = "AssigneeSoapEndPointPort")
    public AssigneeSoapEndPoint getAssigneeSoapEndPointPort() {
        return super.getPort(AssigneeSoapEndPointPort, AssigneeSoapEndPoint.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AssigneeSoapEndPoint
     */
    @WebEndpoint(name = "AssigneeSoapEndPointPort")
    public AssigneeSoapEndPoint getAssigneeSoapEndPointPort(WebServiceFeature... features) {
        return super.getPort(AssigneeSoapEndPointPort, AssigneeSoapEndPoint.class, features);
    }

}
