package com.ajulay.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:52.377+03:00
 * Generated source version: 3.2.7
 */
@WebService(targetNamespace = "http://endpoint.ajulay.com/", name = "AssigneeSoapEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface AssigneeSoapEndPoint {

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/mergeRequest", output = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/mergeResponse")
    @RequestWrapper(localName = "merge", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.MergeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success merge(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<com.ajulay.endpoint.Project> arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/findAssigneeAllByUserIdRequest", output = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/findAssigneeAllByUserIdResponse")
    @RequestWrapper(localName = "findAssigneeAllByUserId", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindAssigneeAllByUserId")
    @ResponseWrapper(localName = "findAssigneeAllByUserIdResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindAssigneeAllByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ajulay.endpoint.Assignee> findAssigneeAllByUserId(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/getByIdRequest", output = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/getByIdResponse")
    @RequestWrapper(localName = "getById", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Project getById(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/createAssigneeRequest", output = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/createAssigneeResponse")
    @RequestWrapper(localName = "createAssignee", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.CreateAssignee")
    @ResponseWrapper(localName = "createAssigneeResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.CreateAssigneeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success createAssignee(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/findAllAssigneeRequest", output = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/findAllAssigneeResponse")
    @RequestWrapper(localName = "findAllAssignee", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindAllAssignee")
    @ResponseWrapper(localName = "findAllAssigneeResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindAllAssigneeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ajulay.endpoint.Assignee> findAllAssignee(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/updateAssigneeRequest", output = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/updateAssigneeResponse")
    @RequestWrapper(localName = "updateAssignee", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.UpdateAssignee")
    @ResponseWrapper(localName = "updateAssigneeResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.UpdateAssigneeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success updateAssignee(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    com.ajulay.endpoint.Assignee arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/deleteAssigneeRequest", output = "http://endpoint.ajulay.com/AssigneeSoapEndPoint/deleteAssigneeResponse")
    @RequestWrapper(localName = "deleteAssignee", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.DeleteAssignee")
    @ResponseWrapper(localName = "deleteAssigneeResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.DeleteAssigneeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success deleteAssignee(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );
}
