package com.ajulay.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:52.112+03:00
 * Generated source version: 3.2.7
 */
@WebService(targetNamespace = "http://endpoint.ajulay.com/", name = "ProjectSoapEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface ProjectSoapEndPoint {

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/ProjectSoapEndPoint/getProjectsRequest", output = "http://endpoint.ajulay.com/ProjectSoapEndPoint/getProjectsResponse")
    @RequestWrapper(localName = "getProjects", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetProjects")
    @ResponseWrapper(localName = "getProjectsResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetProjectsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ajulay.endpoint.Project> getProjects(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/ProjectSoapEndPoint/saveProjectRequest", output = "http://endpoint.ajulay.com/ProjectSoapEndPoint/saveProjectResponse")
    @RequestWrapper(localName = "saveProject", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.SaveProject")
    @ResponseWrapper(localName = "saveProjectResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.SaveProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success saveProject(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    com.ajulay.endpoint.Project arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/ProjectSoapEndPoint/mergeRequest", output = "http://endpoint.ajulay.com/ProjectSoapEndPoint/mergeResponse")
    @RequestWrapper(localName = "merge", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.MergeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success merge(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<com.ajulay.endpoint.Project> arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/ProjectSoapEndPoint/getByIdRequest", output = "http://endpoint.ajulay.com/ProjectSoapEndPoint/getByIdResponse")
    @RequestWrapper(localName = "getById", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Project getById(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/ProjectSoapEndPoint/createProjectByNameRequest", output = "http://endpoint.ajulay.com/ProjectSoapEndPoint/createProjectByNameResponse")
    @RequestWrapper(localName = "createProjectByName", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.CreateProjectByName")
    @ResponseWrapper(localName = "createProjectByNameResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.CreateProjectByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success createProjectByName(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/ProjectSoapEndPoint/getByNameRequest", output = "http://endpoint.ajulay.com/ProjectSoapEndPoint/getByNameResponse")
    @RequestWrapper(localName = "getByName", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetByName")
    @ResponseWrapper(localName = "getByNameResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetByNameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Project getByName(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );
}
