package com.ajulay.endpoint;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:52.119+03:00
 * Generated source version: 3.2.7
 */
@WebServiceClient(name = "ProjectSoapEndPointService",
        wsdlLocation = "http://localhost:8080/project?wsdl",
        targetNamespace = "http://endpoint.ajulay.com/")
public class ProjectSoapEndPointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.ajulay.com/", "ProjectSoapEndPointService");
    public final static QName ProjectSoapEndPointPort = new QName("http://endpoint.ajulay.com/", "ProjectSoapEndPointPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/project?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ProjectSoapEndPointService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8080/project?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ProjectSoapEndPointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ProjectSoapEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProjectSoapEndPointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ProjectSoapEndPointService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ProjectSoapEndPointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ProjectSoapEndPointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns ProjectSoapEndPoint
     */
    @WebEndpoint(name = "ProjectSoapEndPointPort")
    public ProjectSoapEndPoint getProjectSoapEndPointPort() {
        return super.getPort(ProjectSoapEndPointPort, ProjectSoapEndPoint.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ProjectSoapEndPoint
     */
    @WebEndpoint(name = "ProjectSoapEndPointPort")
    public ProjectSoapEndPoint getProjectSoapEndPointPort(WebServiceFeature... features) {
        return super.getPort(ProjectSoapEndPointPort, ProjectSoapEndPoint.class, features);
    }

}
