package com.ajulay.endpoint;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:51.792+03:00
 * Generated source version: 3.2.7
 */
@WebServiceClient(name = "SessionSoapEndPointService",
        wsdlLocation = "http://localhost:8080/login?wsdl",
        targetNamespace = "http://endpoint.ajulay.com/")
public class SessionSoapEndPointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.ajulay.com/", "SessionSoapEndPointService");
    public final static QName SessionSoapEndPointPort = new QName("http://endpoint.ajulay.com/", "SessionSoapEndPointPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/login?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SessionSoapEndPointService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8080/login?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SessionSoapEndPointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SessionSoapEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SessionSoapEndPointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SessionSoapEndPointService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SessionSoapEndPointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SessionSoapEndPointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns SessionSoapEndPoint
     */
    @WebEndpoint(name = "SessionSoapEndPointPort")
    public SessionSoapEndPoint getSessionSoapEndPointPort() {
        return super.getPort(SessionSoapEndPointPort, SessionSoapEndPoint.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns SessionSoapEndPoint
     */
    @WebEndpoint(name = "SessionSoapEndPointPort")
    public SessionSoapEndPoint getSessionSoapEndPointPort(WebServiceFeature... features) {
        return super.getPort(SessionSoapEndPointPort, SessionSoapEndPoint.class, features);
    }

}
