package com.ajulay.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:51.959+03:00
 * Generated source version: 3.2.7
 */
@WebService(targetNamespace = "http://endpoint.ajulay.com/", name = "TaskSoapEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TaskSoapEndPoint {

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/TaskSoapEndPoint/findTaskAllByUserIdRequest", output = "http://endpoint.ajulay.com/TaskSoapEndPoint/findTaskAllByUserIdResponse")
    @RequestWrapper(localName = "findTaskAllByUserId", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindTaskAllByUserId")
    @ResponseWrapper(localName = "findTaskAllByUserIdResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindTaskAllByUserIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ajulay.endpoint.TaskView> findTaskAllByUserId(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/TaskSoapEndPoint/findTaskAllRequest", output = "http://endpoint.ajulay.com/TaskSoapEndPoint/findTaskAllResponse")
    @RequestWrapper(localName = "findTaskAll", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindTaskAll")
    @ResponseWrapper(localName = "findTaskAllResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindTaskAllResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ajulay.endpoint.TaskView> findTaskAll(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/TaskSoapEndPoint/mergeRequest", output = "http://endpoint.ajulay.com/TaskSoapEndPoint/mergeResponse")
    @RequestWrapper(localName = "merge", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.MergeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success merge(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<com.ajulay.endpoint.Project> arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/TaskSoapEndPoint/saveTaskRequest", output = "http://endpoint.ajulay.com/TaskSoapEndPoint/saveTaskResponse")
    @RequestWrapper(localName = "saveTask", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.SaveTask")
    @ResponseWrapper(localName = "saveTaskResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.SaveTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success saveTask(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    com.ajulay.endpoint.TaskView arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/TaskSoapEndPoint/findTaskAllByProjectRequest", output = "http://endpoint.ajulay.com/TaskSoapEndPoint/findTaskAllByProjectResponse")
    @RequestWrapper(localName = "findTaskAllByProject", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindTaskAllByProject")
    @ResponseWrapper(localName = "findTaskAllByProjectResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindTaskAllByProjectResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ajulay.endpoint.TaskView> findTaskAllByProject(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/TaskSoapEndPoint/changeStatusRequest", output = "http://endpoint.ajulay.com/TaskSoapEndPoint/changeStatusResponse")
    @RequestWrapper(localName = "changeStatus", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.ChangeStatus")
    @ResponseWrapper(localName = "changeStatusResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.ChangeStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success changeStatus(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/TaskSoapEndPoint/findTaskByIdRequest", output = "http://endpoint.ajulay.com/TaskSoapEndPoint/findTaskByIdResponse")
    @RequestWrapper(localName = "findTaskById", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindTaskById")
    @ResponseWrapper(localName = "findTaskByIdResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindTaskByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.TaskView findTaskById(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/TaskSoapEndPoint/deleteTaskRequest", output = "http://endpoint.ajulay.com/TaskSoapEndPoint/deleteTaskResponse")
    @RequestWrapper(localName = "deleteTask", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.DeleteTask")
    @ResponseWrapper(localName = "deleteTaskResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.DeleteTaskResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success deleteTask(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );
}
