package com.ajulay.endpoint;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:51.966+03:00
 * Generated source version: 3.2.7
 */
@WebServiceClient(name = "TaskSoapEndPointService",
        wsdlLocation = "http://localhost:8080/task?wsdl",
        targetNamespace = "http://endpoint.ajulay.com/")
public class TaskSoapEndPointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.ajulay.com/", "TaskSoapEndPointService");
    public final static QName TaskSoapEndPointPort = new QName("http://endpoint.ajulay.com/", "TaskSoapEndPointPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/task?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TaskSoapEndPointService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8080/task?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TaskSoapEndPointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TaskSoapEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskSoapEndPointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TaskSoapEndPointService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TaskSoapEndPointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TaskSoapEndPointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns TaskSoapEndPoint
     */
    @WebEndpoint(name = "TaskSoapEndPointPort")
    public TaskSoapEndPoint getTaskSoapEndPointPort() {
        return super.getPort(TaskSoapEndPointPort, TaskSoapEndPoint.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns TaskSoapEndPoint
     */
    @WebEndpoint(name = "TaskSoapEndPointPort")
    public TaskSoapEndPoint getTaskSoapEndPointPort(WebServiceFeature... features) {
        return super.getPort(TaskSoapEndPointPort, TaskSoapEndPoint.class, features);
    }

}
