package com.ajulay.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:52.247+03:00
 * Generated source version: 3.2.7
 */
@WebService(targetNamespace = "http://endpoint.ajulay.com/", name = "UserSoapEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface UserSoapEndPoint {

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/getUsersRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/getUsersResponse")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetUsersResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ajulay.endpoint.User> getUsers(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/mergeRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/mergeResponse")
    @RequestWrapper(localName = "merge", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.Merge")
    @ResponseWrapper(localName = "mergeResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.MergeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success merge(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.util.List<com.ajulay.endpoint.Project> arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/findByIdRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/findByIdResponse")
    @RequestWrapper(localName = "findById", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.User findById(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/getBySurnameRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/getBySurnameResponse")
    @RequestWrapper(localName = "getBySurname", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetBySurname")
    @ResponseWrapper(localName = "getBySurnameResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.GetBySurnameResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.User getBySurname(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/deleteUserRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/deleteUserResponse")
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.DeleteUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success deleteUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/updateUserRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/updateUserResponse")
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.UpdateUserResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success updateUser(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    com.ajulay.endpoint.User arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/changePasswordRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/changePasswordResponse")
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.ChangePasswordResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.Success changePassword(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    com.ajulay.endpoint.User arg1,
            @WebParam(name = "arg2", targetNamespace = "")
                    java.lang.String arg2
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/findByLoginRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/findByLoginResponse")
    @RequestWrapper(localName = "findByLogin", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindByLogin")
    @ResponseWrapper(localName = "findByLoginResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindByLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.ajulay.endpoint.User findByLogin(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );

    @WebMethod
    @Action(input = "http://endpoint.ajulay.com/UserSoapEndPoint/findUserAllByTaskIdRequest", output = "http://endpoint.ajulay.com/UserSoapEndPoint/findUserAllByTaskIdResponse")
    @RequestWrapper(localName = "findUserAllByTaskId", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindUserAllByTaskId")
    @ResponseWrapper(localName = "findUserAllByTaskIdResponse", targetNamespace = "http://endpoint.ajulay.com/", className = "com.ajulay.endpoint.FindUserAllByTaskIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.ajulay.endpoint.User> findUserAllByTaskId(
            @WebParam(name = "arg0", targetNamespace = "")
                    com.ajulay.endpoint.Session arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    java.lang.String arg1
    );
}
