package com.ajulay.endpoint;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import java.net.MalformedURLException;
import java.net.URL;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2019-02-01T13:45:52.253+03:00
 * Generated source version: 3.2.7
 */
@WebServiceClient(name = "UserSoapEndPointService",
        wsdlLocation = "http://localhost:8080/user?wsdl",
        targetNamespace = "http://endpoint.ajulay.com/")
public class UserSoapEndPointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://endpoint.ajulay.com/", "UserSoapEndPointService");
    public final static QName UserSoapEndPointPort = new QName("http://endpoint.ajulay.com/", "UserSoapEndPointPort");

    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/user?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UserSoapEndPointService.class.getName())
                    .log(java.util.logging.Level.INFO,
                            "Can not initialize the default wsdl from {0}", "http://localhost:8080/user?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UserSoapEndPointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UserSoapEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserSoapEndPointService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public UserSoapEndPointService(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public UserSoapEndPointService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public UserSoapEndPointService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }


    /**
     * @return returns UserSoapEndPoint
     */
    @WebEndpoint(name = "UserSoapEndPointPort")
    public UserSoapEndPoint getUserSoapEndPointPort() {
        return super.getPort(UserSoapEndPointPort, UserSoapEndPoint.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UserSoapEndPoint
     */
    @WebEndpoint(name = "UserSoapEndPointPort")
    public UserSoapEndPoint getUserSoapEndPointPort(WebServiceFeature... features) {
        return super.getPort(UserSoapEndPointPort, UserSoapEndPoint.class, features);
    }

}
